config/routes.rb
Duluth::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match '_import' => 'items#import'
  match '_export' => 'items#export'

  match 'token' => 'items#token'

  resources :items

  match ':j' => 'items#ajax_index'
  match ':kind(/:context)' => 'items#index', :as => :kind

  root :to => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :summary, :presence => true

  belongs_to :user
  validates_presence_of :user

  after_create :set_sort

  def set_sort
    unless sort.to_f > 0
      self.sort = id
      save!
    end
  end

  def self.contexts(user)
    contexts = []
    actions(user).each do |item|
      item.summary.scan(/@\w+/).each {|c| contexts << c}
    end
    contexts.uniq.sort
  end

  def self.every(user)
    where(:user_id => user)
  end

  def self.archive(user)
    where(:user_id => user, :archive => true).order(:sort).reverse_order
  end

  def self.active(user)
    where(:user_id => user, :archive => false).order(:sort).reverse_order
  end

  def self.inbox(user)
    active(user).where(:kind => 'inbox')
  end

  def self.projects(user)
    active(user).where(:kind => 'project')
  end

  def self.actions(user)
    active(user).where(:kind => 'action')
  end

  def self.waiting(user)
    active(user).where(:kind => 'waiting')
  end

  def self.maybe(user)
    active(user).where(:kind => 'maybe')
  end

  def self.note(user)
    active(user).where(:kind => 'note')
  end

  def self.calendar(user)
    active(user).where(:kind => 'calendar')
  end

  # TODO this go somewhere else
  def self.csv items
    CSV.generate do |csv|
      csv << ['id', 'kind', 'created_at', 'updated_at', 'archive', 'user_id', 'sort', 'summary', 'body']
      items.each do |i|
        csv << [i.id, i.kind, i.created_at, i.updated_at, i.archive, i.user_id, i.sort, i.summary, i.body]
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :items

  def nick
    email.split(/@/)[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  def ajax_index
    @items = Item.active(current_user)
  end

  # GET /items
  # GET /items.json
  def index
    @item = Item.new

    if params[:kind] && params[:kind] != 'all'
      opts = {:kind => params[:kind]}
    else
      opts = {}
    end

    @items = Item.active(current_user).where(opts)
    if params[:context]
      @items = @items.where("summary LIKE '%#{params[:context]}%'")
    end

    @contexts = Item.contexts(current_user)

    @count = {}
    [:inbox, :action, :project, :waiting, :maybe, :note, :calendar].each do |kind|
      @count[kind] = Item.active(current_user).where(:kind => kind).count
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items, callback: params[:callback] }
      format.text { render file: "items/items.txt.erb" }
      format.csv { send_data(Item.csv(@items),
                             :type => 'text/csv',
                             :filename => "#{current_user.nick}_#{params[:kind]}_#{params[:context]}.csv") }
    end
  end

  def token
    if request.post?
      current_user.reset_authentication_token!
      redirect_to token_path
      return
    else
      current_user.ensure_authentication_token!
    end

    @token = current_user.authentication_token
    respond_to do |format|
      format.html
    end
  end

  def import
    if request.post?
      tmp = params[:file_upload][:my_file].tempfile
      user_id = current_user.id
      CSV.foreach(tmp.path, :headers => true) do |row|
        attrs = row.to_hash
        existing = current_user.items.find_by_summary attrs['summary']

        if existing.present?
          existing.update_attributes attrs
        else
          current_user.items.create! attrs
        end
      end
      redirect_to :items
    end
  end

  def export
    items = Item.every(current_user)
    filename = "duluth_items_#{current_user.nick}.csv"

    send_data(Item.csv(items), :type => 'text/csv', :filename => filename)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html { render layout: false }# show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to request.referer, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { render partial: 'item', locals: { item: @item } }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.archive = true
    @item.save!

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Destroyed item.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_options_helper(item)
    if item.archive?
      opts = [["",
               [["Closed", item.kind],
                ["Re-open", "do:unarchive"]]]]
    else
      opts = [["Move to:",
               [["Inbox", "inbox"],
                ["Project", "project"],
                ["Action", "action"],
                ["Someday/Maybe", "maybe"],
                ["Waiting For", "waiting"],
                ["Note", "note"],
                ["Calendar", "calendar"]]],
              ["Other",
               [["Close", "do:archive"]]]]
    end
    grouped_options_for_select(opts, item.kind)
  end

  def show_count num
    if num && num > 0
      " (#{num.to_i})"
    else
      ""
    end
  end
end

app/views/items/_ajax_focus_bar.html.erb
<div class="focus" style="padding: .5em">
  <ul>
    <li><%= link_to "ALL", kind_path(:all) %></li>
    <li><%= link_to "inbox", kind_path(:inbox) %></li>
    <li><%= link_to "projects", kind_path(:project) %></li>
    <li><%= link_to "actions", kind_path(:action) %></li>
    <li><%= link_to "waiting", kind_path(:waiting) %></li>
    <li><%= link_to "maybe", kind_path(:maybe) %></li>
    <li><%= link_to "notes", kind_path(:note) %></li>
    <li><%= link_to "calendar", kind_path(:calendar) %></li>
  </ul>
</div>

app/views/items/_focus_bar.html.erb
<div class="focus" style="padding: .5em">
  <ul>
    <li><%= link_to "ALL", kind_path(:all) %></li>
    <li><%= link_to "inbox" + show_count(@count[:inbox]), kind_path(:inbox) %></li>
    <li><%= link_to "projects" + show_count(@count[:project]), kind_path(:project) %></li>
    <li><%= link_to "actions" + show_count(@count[:action]), kind_path(:action) %></li>
    <li><%= link_to "waiting" + show_count(@count[:waiting]), kind_path(:waiting) %></li>
    <li><%= link_to "maybe" + show_count(@count[:maybe]), kind_path(:maybe) %></li>
    <li><%= link_to "notes" + show_count(@count[:note]), kind_path(:note) %></li>
    <li><%= link_to "calendar" + show_count(@count[:calendar]), kind_path(:calendar) %></li>
  </ul>
</div>

app/views/items/_form.html.erb
<div id="newform">
  <%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
      <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <span class="field">
    <%= f.text_field :summary, :class => 'focus', :placeholder => 'Enter new item here' %>
  </span>
  <% end %>
</div>

app/views/items/_item.html.erb
<div class="item <%= item.kind %> <%= item.archive ? 'archive' : '' %>" data-id="<%= item.id %>">
  <span class="number hidden">
    <%= item.id %>/<%= item.sort %>
  </span>

  <span class="kind">
    <%= select_tag item.kind, item_options_helper(item) %>
  </span>

  <span class="summary edit"><%= item.summary %></span>

</div>

app/views/items/_list.html.erb
<div class="itemlist">
  <% list.each do |item| %>
  <%= render 'item', item: item %>
  <% end %>
</div>

app/views/items/ajax_index.html.erb
<div class="grid_2">
  <%= render 'ajax_focus_bar' %>
</div>

<div class="grid_10">
  <div id="items">items here</div>
</div>
<div class="clear"></div>

<script>
  var bootstrapped_items = <%= @items.to_json.html_safe %>;
</script>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :notes %> <br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Destroy', @item, confirm: 'Are you sure?', method: :delete %>

<%= link_to 'Back', items_path %>

app/views/items/import.html.erb
<p>Please select a file for import:</p>

<%= form_for :file_upload, :html => {:multipart => true} do |f| %>
  <%= f.file_field :my_file %>
  <%= f.submit "Upload" %>
<% end %>

app/views/items/index.html.erb
<div class="grid_2">
  <%= render 'focus_bar' %>
</div>

<div class="grid_10">
  <%= render 'form' %>
  <%= render 'list', :list => @items %>
</div>
<div class="clear"></div>

app/views/items/items.txt.erb
<% @items.each do |i| %>
<%= i.kind[0].upcase %> (<%= i.id %>) <%= i.summary %>
<% end %>

app/views/items/show.html.erb
<div class="item <%= @item.kind %>">
  <h1><%= @item.summary %></h1>
  <div>
    Created <%= time_ago_in_words(@item.created_at) %> ago
  </div>
  <div>
    Updated <%= time_ago_in_words(@item.updated_at) %> ago
  </div>

  <pre><%= @item.body || 'no body' %></pre>
</div>

app/views/items/token.html.erb
<h1><%= @token %></h1>

<%= form_tag(token_path, :method => "post") do %>
  <%= submit_tag "generate new token" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Duluth</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <div class="container_12">
      <div class="grid_8">
        DULUTH
      </div>

      <div class="signed_in_as">
        <% if user_signed_in? %>
        <div>
          Logged in as <%= current_user.nick %>
          <%= link_to "signout", destroy_user_session_path, :method => :delete %>
        </div>
        <% end %>
      </div>

      <div class="grid_12">
        <div style="text-align: center">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
      <div class="clear"></div>

      <div class="clear"></div>

      <%= yield %>

    </div>

  </body>
</html>